### ISSUE TITLE
Sort observations fails

### ISSUE THREAD

**Issue by pheyvaer** [SolidLabResearch/LDES-in-SOLID-Semantic-Observations-Replay#13]
1. I have downloaded the `dataset_participant1.nt` dataset.
2. I loaded the dataset via 
    ```shell
    curl http://localhost:3001/loadDataset?dataset=dataset_participant1.nt
    ```
3. The loading size is 3591710.
4. The observation count is 718342.
5. When I ask to sort the observations via 
    ```shell
    curl http://localhost:3001?sortObservations
    ```
    I get the following error
    ```html
    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="utf-8">
    <title>Error</title>
    </head>
    <body>
    <pre>Cannot GET /</pre>
    </body>
    </html>
    ```
    I don't see any errors in the CSS or the engine.

**Comment by argahsuknesib** [comment]
This issue should be fixed with the recent pull request, https://github.com/SolidLabResearch/LDES-in-SOLID-Semantic-Observations-Replay/pull/14/commits/452be12fc9fa8e5c6f0ac4c61df7e6c19706e4e1
as it was a typo. 

It should be,
```bash
curl http://localhost:3001/sortObservations
```
instead of,
```bash
curl http://localhost:3001?sortObservations
```
